---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: capa-mp-0
spec:
  clusterName: kind
  replicas: 2 ## this is like... 2 ASG's?
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: EKSConfig
          name: capa-mp-0
      clusterName: kind
      infrastructureRef:
        apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachinePool
        name: capa-mp-0
      version: v1.18.3
---
apiVersion: exp.infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachinePool
metadata:
  name: capa-mp-0
spec:
  minSize: 2
  maxSize: 10
  availabilityZones: us-east-1
  mixedInstancesPolicy:
    launchTemplate:
      overrides:
        - instanceType: "m5.2xlarge"
        - instanceType: "t2.2xlarge"
    instancesDistribution:
      onDemandAllocationStrategy: 70%
      spotAllocationStrategy: 30%
  awsLaunchTemplate:
    iamInstanceProfile: 
    blockDeviceMappings: 
    imageId: "ami-06001cac528f2f10c"
    instanceType: "t2.medium"
    sshKeyName: "confab_development"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: EKSConfig
metadata:
  name: capa-mp-0
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
        cni-bin-dir: /opt/cni/bin
        cni-conf-dir: /etc/cni/net.d
        image-gc-high-threshold: "50"
        image-gc-low-threshold: "45"
        minimum-container-ttl-duration: 1m
        network-plugin: cni
        node-ip: '{{ ds.meta_data.local_ipv4 }}'
      name: '{{ ds.meta_data.hostname }}'
